# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kim Gilbert
tagline:          'PhD Candidate'
description:      ''
url:              http://kjgilbert/github.io

author:
  name:           'Kim Gilbert'
  url:            http://www.zoology.ubc.ca/person/kgilbert

#paginate:         5


github:
  repo:           https://github.com/kjgilbert/kjgilbert.github.io