# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kimberly Gilbert
tagline:          'PhD, Data Scientist'
description:      'PhD, Data Scientist'
url:              http://kjgilbert/github.io

author:
  name:           'Kim Gilbert'
  url:            http://www.zoology.ubc.ca/person/kgilbert

# paginate:         5

github:
  repo:           https://github.com/kjgilbert/kjgilbert/github.io
